### ISSUE TITLE
有时候服务起不来http://127.0.0.1:7001/public/index.html

### ISSUE THREAD

**Issue by packaaa** [JsonMa/swagger-egg#1]
![image](https://user-images.githubusercontent.com/29727412/125764683-ab5fa8e1-a3c4-4cd8-b33a-d7e883321cfb.png)

**Comment by packaaa** [comment]
必须从新下载才能跑起来
![image](https://user-images.githubusercontent.com/29727412/125765746-70e174c3-998d-4869-9e64-51b3f8e20f2c.png)

**Comment by JsonMa** [comment]
> 必须从新下载才能跑起来
> ![image](https://user-images.githubusercontent.com/29727412/125765746-70e174c3-998d-4869-9e64-51b3f8e20f2c.png)

你试试JS项目，TS目前支持得不好，文档里面有提到。

**Comment by packaaa** [comment]
是js项目，现在是只要一有报错，重新启动就起不来服务，必须得从新下载依赖，感觉像是node_moudles有缓存阻塞了egg的服务。

**Comment by JsonMa** [comment]
> 是js项目，现在是只要一有报错，重新启动就起不来服务，必须得从新下载依赖，感觉像是node_moudles有缓存阻塞了egg的服务。

你试试这个[例子](https://github.com/JsonMa/swagger-egg/tree/master/example/egg-swagger-example)，目前看不到其它错误信息。

**Comment by JsonMa** [comment]
> 是js项目，现在是只要一有报错，重新启动就起不来服务，必须得从新下载依赖，感觉像是node_moudles有缓存阻塞了egg的服务。

我用示例测试了下，偶尔确实会出现这个问题，删除node_modules后重新安装依赖就没问题了，后续我再定位下改问题，猜测是插件组塞了egg的启动进程。

**Comment by Marhooo** [comment]
![image](https://user-images.githubusercontent.com/15125523/131655107-9afd5235-57a5-43ad-843c-5d7df5e65787.png)
进程卡住了，cpu一直20%左右

**Comment by JsonMa** [comment]
> ![image](https://user-images.githubusercontent.com/15125523/131655107-9afd5235-57a5-43ad-843c-5d7df5e65787.png)
> 进程卡住了，cpu一直20%左右

是偶尔出现么？
