### ISSUE TITLE
配置controller注释时，parameterSchema中，目前能否支持一些常用类型的配置？

### ISSUE THREAD

**Issue by aixinyongheng** [JsonMa/swagger-egg#11]
@description #parameters {PrameterName} {In} {ParameterSchema} {Required} - {Description}

目前在controller中，是否可以直接在{ParameterSchema}处 直接配置参数的类型，比如常用的 string ,number,object,file 等？

例如：
*@description#parameters  obj  query {number}  false - obj

**Comment by JsonMa** [comment]
> @description #parameters {PrameterName} {In} {ParameterSchema} {Required} - {Description}
> 
> 目前在controller中，是否可以直接在{ParameterSchema}处 直接配置参数的类型，比如常用的 string ,number,object,file 等？
> 
> 例如： *@description#parameters obj query {number} false - obj

OK，但是要支持其它配置就只能通过jsonschema去写了。例如：

![image](https://user-images.githubusercontent.com/13042493/150950815-c8a33694-4722-4b0d-a500-87fa17d4b7d7.png)

**Comment by JsonMa** [comment]
> @description #parameters {PrameterName} {In} {ParameterSchema} {Required} - {Description}
> 
> 目前在controller中，是否可以直接在{ParameterSchema}处 直接配置参数的类型，比如常用的 string ,number,object,file 等？
> 
> 例如： *@description#parameters obj query {number} false - obj

已经实现该功能：
eb448b404e232294232fc7b7769dc926ddae262e
