### ISSUE TITLE
controller文件名带有'-'生成不了api文档

### ISSUE THREAD

**Issue by qzcsgs** [JsonMa/swagger-egg#12]
```js
// router.js
router.resources('xxx-test', '/api/xxx-test', controller.xxxTest);

// controller/xxx-test.js
class XxxTestController extends Controller {
  /**
   * #swagger-api
   * @function index
   * @summary 查询
   * @description #tags xxx-test
   */
  async index() {
      this.ctx.body = 'select!!!';
  }
```

**Comment by JsonMa** [comment]
> ```js
> // router.js
> router.resources('xxx-test', '/api/xxx-test', controller.xxxTest);
> 
> // controller/xxx-test.js
> class XxxTestController extends Controller {
>   /**
>    * #swagger-api
>    * @function index
>    * @summary 查询
>    * @description #tags xxx-test
>    */
>   async index() {
>       this.ctx.body = 'select!!!';
>   }
> ```
你的router应该指定处理方法，例如：controller.xxxTest.index，上面的示例只指定了controller文件，但是没有指定对应controller文件下的方法。

**Comment by qzcsgs** [comment]
> 

你可能看错了是resources这个函数，只需要指定到controller

**Comment by qzcsgs** [comment]
> > ```js
> > // router.js
> > router.resources('xxx-test', '/api/xxx-test', controller.xxxTest);
> > 
> > // controller/xxx-test.js
> > class XxxTestController extends Controller {
> >   /**
> >    * #swagger-api
> >    * @function index
> >    * @summary 查询
> >    * @description #tags xxx-test
> >    */
> >   async index() {
> >       this.ctx.body = 'select!!!';
> >   }
> > ```
> 
> 你的router应该指定处理方法，例如：controller.xxxTest.index，上面的示例只指定了controller文件，但是没有指定对应controller文件下的方法。

你可能看错了是`resources`这个函数，只需要指定到`controller`

**Comment by JsonMa** [comment]
> > > ```js
> > > // router.js
> > > router.resources('xxx-test', '/api/xxx-test', controller.xxxTest);
> > > 
> > > // controller/xxx-test.js
> > > class XxxTestController extends Controller {
> > >   /**
> > >    * #swagger-api
> > >    * @function index
> > >    * @summary 查询
> > >    * @description #tags xxx-test
> > >    */
> > >   async index() {
> > >       this.ctx.body = 'select!!!';
> > >   }
> > > ```
> > 
> > 
> > 你的router应该指定处理方法，例如：controller.xxxTest.index，上面的示例只指定了controller文件，但是没有指定对应controller文件下的方法。
> 
> 你可能看错了是`resources`这个函数，只需要指定到`controller` 而且我实际测试过，将文件上的'-'去掉后，文档可以正常生成

好的，我已经复现了这个BUG，稍后发布一个修复的版本。

**Comment by qzcsgs** [comment]
> > > > ```js
> > > > // router.js
> > > > router.resources('xxx-test', '/api/xxx-test', controller.xxxTest);
> > > > 
> > > > // controller/xxx-test.js
> > > > class XxxTestController extends Controller {
> > > >   /**
> > > >    * #swagger-api
> > > >    * @function index
> > > >    * @summary 查询
> > > >    * @description #tags xxx-test
> > > >    */
> > > >   async index() {
> > > >       this.ctx.body = 'select!!!';
> > > >   }
> > > > ```
> > > 
> > > 
> > > 你的router应该指定处理方法，例如：controller.xxxTest.index，上面的示例只指定了controller文件，但是没有指定对应controller文件下的方法。
> > 
> > 
> > 你可能看错了是`resources`这个函数，只需要指定到`controller` 而且我实际测试过，将文件上的'-'去掉后，文档可以正常生成
> 
> 好的，我已经复现了这个BUG，稍后发布一个修复的版本。

好的，辛苦了
