### ISSUE TITLE
建议暴露ts编译出的 `schemaObject` 以便复用于参数校验

### ISSUE THREAD

**Issue by kerryChen95** [JsonMa/swagger-egg#19]
当配置 `typescriptJsonSchema: true` 时， `app/schema/**/*.ts` 中会编译成 `schemaObject` ，虽然可以在注释中引用 `schemaObject` 进行声明，但看起来没法在 `app/controller/**/*.ts` 的代码中引用 `schemaObject` 。

建议插件把 `schemaObject` 挂载到 `app` 或 `ctx` ，以便复用于 `ctx.valudate(rules, data)` 的规则中，否则需要在 `rules` 中重复声明参数类型等信息。

**Comment by JsonMa** [comment]
v1.7.2版本已经实现了该功能，可通过app.swagger.schema获取！
