### ISSUE TITLE
请问想在apifox里配置出post请求，参数取json，controller里应该怎么配置呢

### ISSUE THREAD

**Issue by MZSY** [JsonMa/swagger-egg#27]
我想在apifox里配置post请求，一般我的post请求都是用的json格式，不是x-www-form-urlencoded的格式，现在我在controller里配置
`* @description #parameters userid formData string true - 用户id`
导入到Apifox以后变成了x-www-form-urlencoded的参数，这样的参数拿到格式不对，请教一下怎么配置

**Comment by JsonMa** [comment]
> 

application-json只能放到请求的body里面，所以应该写成 * @description #parameters userid body schema true - 请求体

**Comment by MZSY** [comment]
好的，我试了可以实现，非常感谢！另外想问下，类似的配置型样例有比较完整的吗，还是就只有您回复里的那个链接地址那些？
我想在body里配置成简单的json串作为传参样例，类似这样的可以吗
![test](https://user-images.githubusercontent.com/54693227/171387058-dc54ff6a-e397-43ad-9c23-bffff6b2e158.png)

**Comment by MZSY** [comment]
我指的是，在代码controller层，swagger那里配置好了直接导入到apifox里可以自动生成这样一种格式的json，能实现吗
`    * @description #parameters body body body true - 用户数据体`
我这样配置body只能出这样的结果
![1](https://user-images.githubusercontent.com/54693227/171527263-dc1955ba-f1f2-4c21-85e6-11ad729f662b.png)

**Comment by JsonMa** [comment]
> 我指的是，在代码controller层，swagger那里配置好了直接导入到apifox里可以自动生成这样一种格式的json，能实现吗 ` * @description #parameters body body body true - 用户数据体` 我这样配置body只能出这样的结果 ![1](https://user-images.githubusercontent.com/54693227/171527263-dc1955ba-f1f2-4c21-85e6-11ad729f662b.png)

你说的是把swagger.json文件导入到apifox里面么？

**Comment by MZSY** [comment]
> > 我指的是，在代码controller层，swagger那里配置好了直接导入到apifox里可以自动生成这样一种格式的json，能实现吗 ` * @description #parameters body body body true - 用户数据体` 我这样配置body只能出这样的结果 ![1](https://user-images.githubusercontent.com/54693227/171527263-dc1955ba-f1f2-4c21-85e6-11ad729f662b.png)
> 
> 你说的是把swagger.json文件导入到apifox里面么？

我的意思是，之前不是问过您怎么把application-json写到controller里吗？这个写入controller并导入到apifox我已经实现了，但是导入进去以后每次调用默认自动生成的是个空的对象，需要手动重新填一遍keyvalue值。那么这个对象参数能不能通过在controller里配置达到生成指定的body格式？
![2-2](https://user-images.githubusercontent.com/54693227/172077476-79fe1b96-0138-444f-86d9-8b6c073fe4f0.png)
![2-1](https://user-images.githubusercontent.com/54693227/172077477-4c76f4e2-4aea-4db4-ad4f-be92690ea257.png)

**Comment by JsonMa** [comment]
> > > 我指的是，在代码controller层，swagger那里配置好了直接导入到apifox里可以自动生成这样一种格式的json，能实现吗 ` * @description #parameters body body body true - 用户数据体` 我这样配置body只能出这样的结果 ![1](https://user-images.githubusercontent.com/54693227/171527263-dc1955ba-f1f2-4c21-85e6-11ad729f662b.png)
> > 
> > 
> > 你说的是把swagger.json文件导入到apifox里面么？
> 
> 我的意思是，之前不是问过您怎么把application-json写到controller里吗？这个写入controller并导入到apifox我已经实现了，但是导入进去以后每次调用默认自动生成的是个空的对象，需要手动重新填一遍keyvalue值。那么这个对象参数能不能通过在controller里配置达到生成指定的body格式？ ![2-2](https://user-images.githubusercontent.com/54693227/172077476-79fe1b96-0138-444f-86d9-8b6c073fe4f0.png) ![2-1](https://user-images.githubusercontent.com/54693227/172077477-4c76f4e2-4aea-4db4-ad4f-be92690ea257.png)

definitions也是需要你去schema文件中定义的，这个没办法自动生成哦。

**Comment by MZSY** [comment]
> > > > 我指的是，在代码controller层，swagger那里配置好了直接导入到apifox里可以自动生成这样一种格式的json，能实现吗 ` * @description #parameters body body body true - 用户数据体` 我这样配置body只能出这样的结果 ![1](https://user-images.githubusercontent.com/54693227/171527263-dc1955ba-f1f2-4c21-85e6-11ad729f662b.png)
> > > 
> > > 
> > > 你说的是把swagger.json文件导入到apifox里面么？
> > 
> > 
> > 我的意思是，之前不是问过您怎么把application-json写到controller里吗？这个写入controller并导入到apifox我已经实现了，但是导入进去以后每次调用默认自动生成的是个空的对象，需要手动重新填一遍keyvalue值。那么这个对象参数能不能通过在controller里配置达到生成指定的body格式？ ![2-2](https://user-images.githubusercontent.com/54693227/172077476-79fe1b96-0138-444f-86d9-8b6c073fe4f0.png) ![2-1](https://user-images.githubusercontent.com/54693227/172077477-4c76f4e2-4aea-4db4-ad4f-be92690ea257.png)
> 
> definitions也是需要你去schema文件中定义的，这个没办法自动生成哦。

[swagger-egg](https://github.com/JsonMa/swagger-egg)/[example](https://github.com/JsonMa/swagger-egg/tree/master/example)/egg-swagger-ts-schema-example/
这个路径下的配置可以参考吗

**Comment by JsonMa** [comment]
> > > > > 我指的是，在代码controller层，swagger那里配置好了直接导入到apifox里可以自动生成这样一种格式的json，能实现吗 ` * @description #parameters body body body true - 用户数据体` 我这样配置body只能出这样的结果 ![1](https://user-images.githubusercontent.com/54693227/171527263-dc1955ba-f1f2-4c21-85e6-11ad729f662b.png)
> > > > 
> > > > 
> > > > 你说的是把swagger.json文件导入到apifox里面么？
> > > 
> > > 
> > > 我的意思是，之前不是问过您怎么把application-json写到controller里吗？这个写入controller并导入到apifox我已经实现了，但是导入进去以后每次调用默认自动生成的是个空的对象，需要手动重新填一遍keyvalue值。那么这个对象参数能不能通过在controller里配置达到生成指定的body格式？ ![2-2](https://user-images.githubusercontent.com/54693227/172077476-79fe1b96-0138-444f-86d9-8b6c073fe4f0.png) ![2-1](https://user-images.githubusercontent.com/54693227/172077477-4c76f4e2-4aea-4db4-ad4f-be92690ea257.png)
> > 
> > 
> > definitions也是需要你去schema文件中定义的，这个没办法自动生成哦。
> 
> [swagger-egg](https://github.com/JsonMa/swagger-egg)/[example](https://github.com/JsonMa/swagger-egg/tree/master/example)/egg-swagger-ts-schema-example/ 这个路径下的配置可以参考吗

这是TS的示例，如果你不是用的TS就没有参考意义。

**Comment by MZSY** [comment]
> > > > > > 我指的是，在代码controller层，swagger那里配置好了直接导入到apifox里可以自动生成这样一种格式的json，能实现吗 ` * @description #parameters body body body true - 用户数据体` 我这样配置body只能出这样的结果 ![1](https://user-images.githubusercontent.com/54693227/171527263-dc1955ba-f1f2-4c21-85e6-11ad729f662b.png)
> > > > > 
> > > > > 
> > > > > 你说的是把swagger.json文件导入到apifox里面么？
> > > > 
> > > > 
> > > > 我的意思是，之前不是问过您怎么把application-json写到controller里吗？这个写入controller并导入到apifox我已经实现了，但是导入进去以后每次调用默认自动生成的是个空的对象，需要手动重新填一遍keyvalue值。那么这个对象参数能不能通过在controller里配置达到生成指定的body格式？ ![2-2](https://user-images.githubusercontent.com/54693227/172077476-79fe1b96-0138-444f-86d9-8b6c073fe4f0.png) ![2-1](https://user-images.githubusercontent.com/54693227/172077477-4c76f4e2-4aea-4db4-ad4f-be92690ea257.png)
> > > 
> > > 
> > > definitions也是需要你去schema文件中定义的，这个没办法自动生成哦。
> > 
> > 
> > [swagger-egg](https://github.com/JsonMa/swagger-egg)/[example](https://github.com/JsonMa/swagger-egg/tree/master/example)/egg-swagger-ts-schema-example/ 这个路径下的配置可以参考吗
> 
> 这是TS的示例，如果你不是用的TS就没有参考意义。

好的，那我再研究一下，感谢解答
