### ISSUE TITLE
默认路径问题

### ISSUE THREAD

**Issue by Fiseast** [JsonMa/swagger-egg#28]
默认路径是这样的，http://127.0.0.1:7001/swagger-ui.html
但是我想配置如，http://127.0.0.1:7001/docs-api/swagger-ui.html

**Comment by JsonMa** [comment]
/public/index.html

> 默认路径是这样的，http://127.0.0.1:7001/swagger-ui.html 但是我想配置如，http://127.0.0.1:7001/docs-api/swagger-ui.html

路径是这个 /public/index.html
