### ISSUE TITLE
支持 ts 项目上有什么难点吗？

### ISSUE THREAD

**Issue by ken1987** [JsonMa/swagger-egg#3]
目前我在项目中用的是 ts 来开发，目前支持 ts 项目上有什么问题吗？

**Comment by JsonMa** [comment]
> 目前我在项目中用的是 ts 来开发，目前支持 ts 项目上有什么问题吗？

目前我们项目JS比较多，TS有需求的话可以最近改一下发布。

**Comment by Achilles822** [comment]
> > 目前我在项目中用的是 ts 来开发，目前支持 ts 项目上有什么问题吗？
> 
> 目前我们项目JS比较多，TS有需求的话可以最近改一下发布。

希望尽快发布支持ts的版本

**Comment by JsonMa** [comment]
> > > 目前我在项目中用的是 ts 来开发，目前支持 ts 项目上有什么问题吗？
> > 
> > 
> > 目前我们项目JS比较多，TS有需求的话可以最近改一下发布。
> 
> 希望尽快发布支持ts的版本

这周末吧，我抽时间弄出来。

**Comment by smackgg** [comment]
@JsonMa Ts 还没有弄么 。。

**Comment by JsonMa** [comment]
> @JsonMa Ts 还没有弄么 。。

已经支持了哈。使用方式可参考example目录。
