### ISSUE TITLE
如何设置全局变量？

### ISSUE THREAD

**Issue by jeromexiong** [JsonMa/swagger-egg#4]
大部分接口都是需要token等头信息验证才能访问的，该如何设置呢？

**Comment by JsonMa** [comment]
> 大部分接口都是需要token等头信息验证才能访问的，该如何设置呢？

swagger可以设置Authrize，通过请求头带过去。

**Comment by JsonMa** [comment]
> > 大部分接口都是需要token等头信息验证才能访问的，该如何设置呢？
> 
> swagger可以设置Authrize，通过请求头带过去。
