### ISSUE TITLE
swagger-egg/example/egg-swagger-example/  运行效果没有路由接口信息

### ISSUE THREAD

**Issue by kyrieLiu** [JsonMa/swagger-egg#5]
![image](https://user-images.githubusercontent.com/16189974/130323867-d0857f47-2333-4473-ab72-69c2a55cebe4.png)

npm run dev之后访问index.html,页面能出来,但是没有显示定义的接口API文档

**Comment by kyrieLiu** [comment]
![image](https://user-images.githubusercontent.com/16189974/130454528-8f3674b9-093b-4ba5-82e7-32829e998c81.png)

我就是运行的demo

**Comment by JsonMa** [comment]
> ![image](https://user-images.githubusercontent.com/16189974/130454528-8f3674b9-093b-4ba5-82e7-32829e998c81.png)
> 
> 我就是运行的demo

User tag 在config里面定义了，但是实际额controller里面并没有用到，所以生成的文档里面并没有内容。Home Tag因为有被controller用到，所以数据是正确的。
