### ISSUE TITLE
多个路由文件怎么写？我的一直显示不了

### ISSUE THREAD

**Issue by Yxliam** [JsonMa/swagger-egg#6]
![image](https://user-images.githubusercontent.com/16329468/137666555-37d681d4-5fee-429a-ab92-a1c278ebcc52.png)

**Comment by JsonMa** [comment]
> 看了下源码这块不支持router文件夹下有多个路由文件 ![image](https://user-images.githubusercontent.com/16329468/137851484-419fc7e8-59fa-4ebf-b94b-933edda78493.png)

![image](https://user-images.githubusercontent.com/13042493/138012284-a0f44b28-722c-4070-b104-641d24e33033.png)
k可以参考下单元测试中的写法。
